chibisov/drf-extensions

- rest_framework_extensions/cache/decorators.py
- rest_framework_extensions/key_constructor/bits.py
- tests_app/tests/unit/cache/decorators/tests.py
- tests_app/tests/unit/key_constructor/bits/tests.py
- QueryStringKeyBit can use all the query string parameters if `*` is passed
- new flag `cache_errors` in CacheResponse to not cache responses with 4xx or 5xx errors
> QueryStringKeyBit catch all params and do not cache errors flag in CacheResponse

- rest_framework_extensions/bulk_operations/mixins.py
- tests_app/tests/functional/cache/decorators/tests.py
Import 'force_text' from compat in every place. Should now work with Django 1.4. 
Similiar to this one: https://github.com/chibisov/drf-extensions/pull/64
> Use force_text from compat

- docs/index.md
- rest_framework_extensions/key_constructor/bits.py
- tests_app/tests/unit/key_constructor/bits/tests.py
- tox.ini
- Stop unit tests upon first fail: there's no need to continue further in the tests
- Args, Kwargs and Query KeyBits have params set to '*' by default: having any of this key bits without '*' is meaningless
> Fail fast on unit tests and default params for key bits

- rest_framework_extensions/key_constructor/bits.py
- tests_app/tests/unit/key_constructor/bits/tests.py
As noted in #92, the PaginationKeyBit has been non-functional since DRF 3.1 due to the new pagination api.  http://www.django-rest-framework.org/topics/3.1-announcement/#pagination  
This means all pages of a result have the same key, and it becomes impossible to view any other paginated results except for the first page.
This PR updates the PaginationKeyBit to follow the new api.
Thanks for your work on these extensions.
This closes #92.
> Update PaginationKeyBit to work with new DRF Pagination API

- rest_framework_extensions/mixins.py
If a route such as /users/NOT_AN_INTEGER/settings would be
requested and the /users endpoint expects an integer as the second
part of the url then this request would throw a internal server error.
Discussion about this can be found at #86
> Add a fix for failing queryset filters in nested routes

- rest_framework_extensions/routers.py
This PR adds support for the `@detail_route` and  `@list_route` decorators on the nested routers.
> Make `@detail_route` and `@list_route` work with the drf-extensions routers

- rest_framework_extensions/routers.py
It allows a better integration with drf>3.0 that sligthly changes the `class APIRoot`
It is not my decision to remove support of drf 2.4.2 and older, but I think it should be the right thing to do here. Instead of my patch, we could remove the override of `get_api_root_view(self):` method instead.
> drf-extensions can use the DefaulView provided by since DRF version 2.4.3

- rest_framework_extensions/routers.py
- tests_app/tests/unit/routers/nested_router_mixin/tests.py
- tests_app/tests/unit/routers/nested_router_mixin/views.py
When nesting viewsets over 2 levels deep, only the last parent's `lookup_value_regex` is considered.
Take the following viewsets:
``` python
class UserViewSet(ModelViewSet):
lookup_value_regex = 'XXX'
model = UserModel
class GroupViewSet(ModelViewSet):
lookup_value_regex = 'YYY'
model = GroupModel
class PermissionViewSet(ModelViewSet):
lookup_value_regex = 'ZZZ'
model = PermissionModel
```
routed with:
``` python
router = ExtendedSimpleRouter()
(
router.register(r'users', UserViewSet, 'user')
.register(r'groups', GroupViewSet, 'users-group',
parents_query_lookups=['user'])
.register(r'permissions', PermissionViewSet,
'users-groups-permission', parents_query_lookups=[
'group__user',
'group',
]
)
)
```
I would expect this to generate the following urls:
``` …
```
> Nested routes with over 2 levels don't respect `lookup_value_regex`

- .travis.yml
- rest_framework_extensions/etag/decorators.py
- tox.ini
This is just a really fix which fixes some of the Tox tests and a bug we where having where no responses where coming back as 304.
It looks like Django's `parse_tags()` ([django/utils/http.py](https://github.com/django/django/blob/550cb3a365dee4edfdd1563224d5304de2a57fda/django/utils/http.py#L222-L233)) was changed in a Django commit https://github.com/django/django/commit/4ef0e019b7dd3d2bf93b5c705b3b7df9cdb77561to because of issue [27083](https://code.djangoproject.com/ticket/27083) to return ETags with the quotes around. Instead of `123` it is now `"123"`.
I have just made it strip out the `"` characters which is probably a bad fix but it preserves backward compatibility and is nice and simple.
If you have a nicer suggestion let me know so we can use it in our project. Might help …
> Started Django 1.11 support #187

- rest_framework_extensions/routers.py
- rest_framework_extensions/utils.py
- tests_app/tests/functional/key_constructor/bits/views.py
- tests_app/tests/functional/mixins/list_destroy_model_mixin/views.py
- tests_app/tests/functional/mixins/list_update_model_mixin/views.py
- tests_app/tests/unit/utils/tests.py
- tox.ini
We sometimes uses fixes that are in rest-framework's master, but not published yet. So me create a wheel `X.Y.PATCHpreCOMMITHASH` (something like `1.2.3pre8843d7f92416211de9ebb963ff4ce28125932878`) and somehow, `drf-extensions` actually chokes on it.
This uses `distutils` which is in the Python 2 and Python 3 standard library to parse the django-rest-framework's version.
> Parse rest-framework's version by using more tolerant functions

- rest_framework_extensions/cache/decorators.py
- tests_app/tests/unit/cache/decorators/tests.py
When caching the whole response object from DRF, that means
it will include data attribute and the serialiser object.
Now we only explicitly cache what's needed for an HttpResponse.
> Cache only the renered response the whole response object

- docs/index.html
- docs/index.md
- rest_framework_extensions/key_constructor/bits.py
- tests_app/tests/unit/key_constructor/bits/tests.py
Django 2.0 removed support for calling is_authenticated as a function.
This PR changes all accesses to is_authenticated to use the property
version, which has been available since at least 1.11.
The last commit should probably be undone, but i'm unsure how to fix the actual root cause: ```This test was failing. Not sure whether this is the right fix, as i
couldn't quite figure out what was wrong from the issue linked in the
description.```
> Use property is_authenticated instead for django 2.0 compatability

- docs/index.md
GEOIP_CITY instead of GEOIP_COUNTRY in CityKeyConstructor
> Misprint fix in docs example of key constructor params

- docs/index.md
Other question,[ 0.4.0 has been released ](https://pypi.org/project/drf-extensions/) Sept 2018, but the GitHub hosted docs have not been updated: https://chibisov.github.io/drf-extensions/docs/#release-notes
> Fix broken DRF link

- rest_framework_extensions/mixins.py
added an import to rest_framework.mixins to allow direct importing of ListDestroyModelMixin
It appears that this is why ListUpdateModelMixin is imported into mixins (to facilitate direct importing), and the documentation also thinks that it is currently possible to directly import ListDestroyModelMixin. It isn't, this import makes it possible.
> Allow direct importing of ListDestroyModelMixin from rest_framework_extensions.mixins

- tests_app/tests/functional/key_constructor/bits/tests.py
- tests_app/tests/functional/mixins/detail_serializer_mixin/tests.py
- tests_app/tests/functional/mixins/list_destroy_model_mixin/tests.py
- tests_app/tests/functional/mixins/list_update_model_mixin/tests.py
- tests_app/tests/functional/permissions/extended_django_object_permissions/tests.py
- tests_app/tests/functional/routers/extended_default_router/tests.py
- tests_app/tests/functional/routers/nested_router_mixin/tests.py
- tests_app/tests/unit/_etag/decorators/tests.py
- tests_app/tests/unit/cache/decorators/tests.py
- tests_app/tests/unit/key_constructor/bits/tests.py
- tests_app/tests/unit/key_constructor/constructor/tests.py
- tests_app/tests/unit/routers/nested_router_mixin/tests.py
Forgot to clean project itself from usage of deprecated in #288 `rest_framework_extensions.test` module
> delete rest_framework_extensions.test module usage in tests

- rest_framework_extensions/key_constructor/bits.py
https://docs.djangoproject.com/en/dev/releases/3.1/#id1
> Update EmptyResultSet import for django 3.1 compat

- README.md
- rest_framework_extensions/serializers.py
- tests_app/tests/unit/serializers/serializers.py
- tests_app/tests/unit/serializers/tests.py
- tox.ini
To fix https://github.com/chibisov/drf-extensions/issues/291.
Note that in order to have a failing test, I had to replace
```python
saved_object = serializer.save()
```
with
```python
serializer.save()
self.comment.refresh_from_db()
```
because the partial serializer actually puts the data into the instance, but merely does not save it due to `update_fields` being incomplete. So IMO we should refactor the other tests, too.
> fix(PartialUpdateSerializerMixin): support nesting on same instance

- tests_app/tests/unit/routers/nested_router_mixin/tests.py
- tests_app/testutils.py
- tox.ini
DRF dropped rest_framework.compat.get_regex_pattern as it dropped
support for Django < 2. As drf-extensions already does not support
Django < 2, just replay here the same change made in DRF.
> Make tests pass with DRF 3.12

- rest_framework_extensions/cache/decorators.py
- tests_app/tests/unit/cache/decorators/tests.py
- tox.ini
fix #306 
This PR removes the use of _headers when we are on django 3.2 and onwards but keeps it for 3.0 and 3.1. the `.items` method was introduced in django 3.0 and `_headers` attribute was removed in 3.2.
> django 3.2 compatibility : do not use _headers

- docs/index.md
current link leads to a 404 + not https by default.
> fix link to drf docs for viewsets

- rest_framework_extensions/utils.py
This PR solves the open issue #318 .
* Deprecated lib: `distutils`;
* In favor of: `packaging`.
> #318 Removing deprecated lib (distutils)

- tests_app/tests/unit/cache/decorators/tests.py
- tests_app/tests/unit/key_constructor/bits/tests.py
- tests_app/tests/unit/key_constructor/constructor/tests.py
- tests_app/testutils.py
This code pattern is laready used here:
[tests_app/tests/unit/utils/tests.py](https://github.com/chibisov/drf-extensions/blob/9df8f8962e25ef6382cb93f94e3318176e89c8ba/tests_app/tests/unit/utils/tests.py#L4)
----
https://github.com/testing-cabal/mock
mock is now part of the Python standard library, available as [unittest.mock](https://docs.python.org/dev/library/unittest.mock.html) in Python 3.3 onwards.
> prefer new unittest.mock everywhere

- tests_app/tests/functional/mixins/detail_serializer_mixin/urls.py
- tests_app/tests/functional/mixins/list_destroy_model_mixin/urls.py
- tests_app/tests/functional/mixins/list_update_model_mixin/urls.py
- tests_app/tests/functional/mixins/paginate_by_max_mixin/urls.py
- tests_app/tests/functional/permissions/extended_django_object_permissions/urls.py
Since DRF 3.15.0 a unique basename must be used due https://github.com/encode/django-rest-framework/pull/8438
Fixes #341
> tests: Use basename='xxx' to set a unique basename
